### PR TITLE
Update input names to id so the labels can focus them upon click/tap.…

### LINKED ISSUE #7: Change input names to IDs
**Expected Label Behavior**
Upon click or tap of label, it will focus the associated input.

**Current Behavior**
Clicking or tapping the label does not focus the associate input.

**Proposed Solution**
- [ ] Change the input `name` to `id`

### PR DESCRIPTION
**Pull request by ryanfurrer**
Closes #7 
- Update input `name` attribute to `id` in `/app/me/page.tsx` so the labels will focus the inputs upon click/tap.
- Added `id` props to the `Input` and `Checkbox` components for this same purpose

https://github.com/fullstack-chat/fullstack.chat/assets/40150036/61333727-3666-4c29-b08b-9917a1d5c41d

### CODE REVIEW

**Comment by ryanfurrer** [comment]
Latest commit, [c0c23ea](https://github.com/fullstack-chat/fullstack.chat/pull/10/commits/c0c23ea65f8237fd92081205947eb75414278087), Closes "Display social media icons on each profile card" on #5 

CleanShot 2024-05-18Arc000931@2x

**Comment by bmorrisondev** [comment]
Appreciate your efforts man! Would you mind making them a bit smaller? They take too much attention visually with the size they are now

**Comment by ryanfurrer** [comment]
> Appreciate your efforts man! Would you mind making them a bit smaller? They take too much attention visually with the size they are now

🫡

**Comment by ryanfurrer** [comment]
Updates to UserCards

**Review by bmorrisondev — APPROVED** [review]

**Pull request merged**
